name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'

env:
  DOCKERFILE: Dockerfile
  TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Check Out Repo
        uses: actions/checkout@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./${{ env.DOCKERFILE }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
